In [ ]:
import  numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('spam.csv')

In [ ]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.shape

(5572, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [ ]:
df.duplicated().sum()

np.int64(415)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Category'].value_counts()

Category
ham     4516
spam     641
Name: count, dtype: int64

In [ ]:
df=pd.get_dummies(df,columns=['Category'],drop_first=True)

In [ ]:
df.head()

                                             Message  Category_spam
0  Go until jurong point, crazy.. Available only ...          False
1                      Ok lar... Joking wif u oni...          False
2  Free entry in 2 a wkly comp to win FA Cup fina...           True
3  U dun say so early hor... U c already then say...          False
4  Nah I don't think he goes to usf, he lives aro...          False

In [ ]:
df['Category_spam']=df['Category_spam'].astype('int')

In [ ]:
df.head()

                                             Message  Category_spam
0  Go until jurong point, crazy.. Available only ...              0
1                      Ok lar... Joking wif u oni...              0
2  Free entry in 2 a wkly comp to win FA Cup fina...              1
3  U dun say so early hor... U c already then say...              0
4  Nah I don't think he goes to usf, he lives aro...              0

In [ ]:
X=df['Message']
y=df['Category_spam']

In [ ]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5157, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_count=v.fit_transform(X_train)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test_count=v.transform(X_test)

In [ ]:
X_train_dense=X_train_count.toarray()
X_test_dense=X_test_count.toarray()

In [ ]:
models={
    "LogisticRegression":LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(),
    "SVM": SVC(C=1,kernel="rbf")
}

In [ ]:
result=[]

In [ ]:
for name, model in models.items():
  model.fit(X_train_dense, y_train)
  y_pred=model.predict(X_test_dense)
  result.append(
      {
          "Model":name,
          "Accuracy_score": round(accuracy_score(y_test,y_pred),4),
          "F1_score": round(f1_score(y_test,y_pred),4),
          "Classification Report": classification_report(y_test,y_pred),
          "Confusion Matrix": confusion_matrix(y_test,y_pred)
      }
  )

In [ ]:
for i in result:
  for k, val in i.items():
    print(f"{k} : {val}")

Model : LogisticRegression
Accuracy_score : 0.9806
F1_score : 0.9231
Classification Report :               precision    recall  f1-score   support

           0       0.98      1.00      0.99       896
           1       0.97      0.88      0.92       136

    accuracy                           0.98      1032
   macro avg       0.98      0.94      0.96      1032
weighted avg       0.98      0.98      0.98      1032

Confusion Matrix : [[892   4]
 [ 16 120]]
Model : KNN
Accuracy_score : 0.9147
F1_score : 0.5217
Classification Report :               precision    recall  f1-score   support

           0       0.91      1.00      0.95       896
           1       1.00      0.35      0.52       136

    accuracy                           0.91      1032
   macro avg       0.96      0.68      0.74      1032
weighted avg       0.92      0.91      0.90      1032

Confusion Matrix : [[896   0]
 [ 88  48]]
Model : Naive Bayes
Accuracy_score : 0.9109
F1_score : 0.7294
Classification Report :               precision    recall  f1-score   support

           0       0.99      0.91      0.95       896
           1       0.61      0.91      0.73       136

    accuracy                           0.91      1032
   macro avg       0.80      0.91      0.84      1032
weighted avg       0.94      0.91      0.92      1032

Confusion Matrix : [[816  80]
 [ 12 124]]
Model : Decision Tree
Accuracy_score : 0.9622
F1_score : 0.8582
Classification Report :               precision    recall  f1-score   support

           0       0.98      0.98      0.98       896
           1       0.85      0.87      0.86       136

    accuracy                           0.96      1032
   macro avg       0.91      0.92      0.92      1032
weighted avg       0.96      0.96      0.96      1032

Confusion Matrix : [[875  21]
 [ 18 118]]
Model : SVM
Accuracy_score : 0.9816
F1_score : 0.9266
Classification Report :               precision    recall  f1-score   support

           0       0.98      1.00      0.99       896
           1       0.98      0.88      0.93       136

    accuracy                           0.98      1032
   macro avg       0.98      0.94      0.96      1032
weighted avg       0.98      0.98      0.98      1032

Confusion Matrix : [[893   3]
 [ 16 120]]

| Feature                      | Logistic Regression                       | Naive Bayes                                  |
| ---------------------------- | ----------------------------------------- | -------------------------------------------- |
| Type                         | Discriminative Model                      | Generative Model                             |
| Goal                         | Directly predicts class probability       | Calculates probability using Bayes' theorem  |
| Formula                      | Uses Sigmoid Function                     | Uses Bayes Theorem                           |
| Assumption                   | No strong feature independence assumption | Assumes all features are independent         |
| Training Speed               | Slower                                    | Faster                                       |
| Dataset Size                 | Needs more data                           | Works well even with small data              |
| Handling Correlated Features | Handles better                            | Performance drops if features are correlated |
| Output                       | Probability of class directly             | Conditional probability of class             |
| Overfitting                  | Less likely                               | Usually less prone due to simplicity         |
| Interpretability             | Coefficients show feature impact          | Probabilities show feature contribution      |